### ISSUE TITLE
Efi special pool question

### ISSUE THREAD

**Issue by BrentHoltsclaw** [Microsoft/MS_UEFI#1]
Within MS_UEFI/MdeModulePkg/Library/EfiSpecialPoolLib/SpecialPoolLib.c, is line 92 correct  
`if ((0x01 << PoolType) && PcdGet32(PcdSpecialPoolTypes)) {` 
or should it be 
`if ((0x01 << PoolType) & PcdGet32(PcdSpecialPoolTypes)) {`

**Comment by mikeytdisco** [comment]
You are correct, it should be the bit-wise AND "&".

**Comment by mikeytdisco** [comment]
added a different implementation of EfiSpecialPool for standalone integration and additional bug fixes.  See https://github.com/Microsoft/MS_UEFI/tree/share/EfiSpecialPoolV2

**Comment by spbrogan** [comment]
@BrentHoltsclaw  - Your issue was fixed along with a few other issues.  Thanks for taking a look and reporting the issue to us.  TianoCore is also working on a similar feature and we eventually hope to replace our stand alone implementation with theirs which is embedded in the core memory management code.    Thanks again.
